version: '3'
services:

  # Production services
  
  mongodbusers:
    container_name: mongodbusers-${teamname:-wiq_es05b}
    image: mongo
    profiles: ["dev", "prod"]
    volumes:
      - users_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mynetwork
    restart: always
  
  mongodbquestions:
    container_name: mongodbquestions-${teamname:-wiq_es05b}
    image: mongo
    profiles: ["dev", "prod"]
    volumes:
      - questions_data:/data/db
    ports:
      - "27018:27018"
    networks:
      - mynetwork
    restart: always

  mongodbhistory:
    container_name: mongodbquestions-${teamname:-wiq_es05b}
    image: mongo
    profiles: ["dev", "prod"]
    volumes:
      - history_data:/data/db
    ports:
      - "27019:27019"
    networks:
      - mynetwork
    restart: always
  

  postgres:
    container_name: postgres-${teamname:-wiq_es05b}
    image: postgres
    profiles: ["dev", "prod"]
    volumes:
      - postgres_data:/data/db
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    environment:
      POSTGRES_PASSWORD: jordishhh
    restart: always

  webapp:
    container_name: webapp-${teamname:-wiq_es05b}
    image: ghcr.io/arquisoft/wiq_es05b/webapp:latest
    profiles: ["dev", "prod"]
    build:
      context: ./webapp
      args:
        SSL_API_URI: ${ssl_api_uri:-http://localhost:8000}
        API_URI: ${api_uri:-http://localhost:8000}
    depends_on:
      - gatewayservice
    networks:
      - mynetwork
    ports:
      - "3000:3000"
    restart: always

  gatewayservice:
    container_name: gatewayservice-${teamname:-wiq_es05b}
    image: ghcr.io/arquisoft/wiq_es05b/gatewayservice:latest
    profiles: ["dev", "prod"]
    build: ./gatewayservice
    depends_on:
      - mongodb
      - userservice
      - authservice
      - history
      - jordi-ask
      - jordi-think
      - ranking
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    environment:
      AUTH_SERVICE_URL: http://authservice:8002
      USER_SERVICE_URL: http://userservice:8001
      JORDI_THINK_SERVICE_URL: http://jordi-think:8003
      JORDI_ASK_SERVICE_URL: http://jordi-ask:8004
      RANKING_SERVICE_URL: http://ranking:8005
      HISTORY_SERVICE_URL: http://history:8006
    restart: always

  userservice:
    container_name: userservice-${teamname:-wiq_es05b}
    image: ghcr.io/arquisoft/wiq_es05b/userservice:latest
    profiles: ["dev", "prod"]
    build: ./users/userservice
    depends_on:
      - mongodb
    ports:
      - "8001:8001"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb
    restart: always

  authservice:
    container_name: authservice-${teamname:-wiq_es05b}
    image: ghcr.io/arquisoft/wiq_es05b/authservice:latest
    profiles: ["dev", "prod"]
    build: ./users/authservice
    depends_on:
      - mongodb
    ports:
      - "8002:8002"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb
      SECRET: a-very-secret-string
    restart: always

  jordi:
    container_name: jordi-${teamname:-wiq_es05b}
    image: ghcr.io/arquisoft/wiq_es05b/jordi:latest
    profiles: ["dev", "prod"]
    build: ./jordi
    ports:
      - "8003:8003"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/questions
    restart: always

  history:
    container_name: history-${teamname:-wiq_es05b}
    image: ghcr.io/arquisoft/wiq_es05b/history:latest
    profiles: ["dev", "prod"]
    build: ./userhistory
    depends_on:
      - mongodb
    ports:
      - "8004:8004"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/history
    restart: always

  ranking:
    container_name: ranking-${teamname:-wiq_es05b}
    image: ghcr.io/arquisoft/wiq_es05b/ranking:latest
    profiles: ["dev", "prod"]
    build: ./ranking
    ports:
      - "8005:8005"
    networks:
      - mynetwork
    environment:
      POSTGRES_URI: postgres://postgres:5432/ranking
    restart: always

  reverse-proxy:
    container_name: reverse-proxy-${teamname:-wiq_es05b}
    image: ghcr.io/arquisoft/wiq_es05b/proxy:latest
    profiles: ["prod"]
    build: ./proxy
    depends_on:
      - gatewayservice
      - webapp
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mynetwork
    restart: always

  # Development services

  prometheus:
    image: prom/prometheus
    container_name: prometheus-${teamname:-wiq_es05b}
    profiles: ["dev"]
    networks:
      - mynetwork
    volumes:
      - ./gatewayservice/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on: 
      - gatewayservice
      
  grafana:
    image: grafana/grafana
    container_name: grafana-${teamname:-wiq_es05b}
    profiles: ["dev"]
    networks:
      - mynetwork
    volumes:
      - grafana_data:/var/lib/grafana
      - ./gatewayservice/monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SERVER_HTTP_PORT=9091
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "9091:9091"
    depends_on: 
      - prometheus

volumes:
  users_data:
  questions_data:
  postgres_data:
  prometheus_data:
  grafana_data:
  history_data:

networks:
  mynetwork:
    driver: bridge
