ifndef::imagesdir[:imagesdir: ../images]

[[section-architecture-constraints]]
== Architecture Constraints


=== 1. Technical Constraints

These constraints are set by the project, and we believe that altering them would be counterproductive, therefore, we have chosen to adhere to them.

=== 1. Technical Constraints

|===
| Constraint | Explanation

|*_Wikidata_*
| This project will be using wikidata to retrieve the source of the game questions

|===

=== 2. Organizational Constraints

|===
| Constraint | Explanation

|*_Team_*
| Our team consists of five members who are new to collaborating with each other.

|*_Time_*
| Deadline at the end of the semester,
the time is divided among two hours per week of in-class work, multiple meetings with team members, and individual self-work.
We'll also have four deliverables spaced every two weeks, where we'll receive feedback from the instructor.

|*_Testing_*
| Various scenarios will be explored to accurately assess the application's functionality.
Diverse testing techniques will be employed to achieve comprehensive coverage, aiming for
the highest possible quality assurance. We also work with different levels of testing,
including unit, integration, load, and system testing. Additionally, a shift-left testing
approach will be used, where testing is performed as early as possible in the development
process, following dynamics like Behaviour Driven Development (BDD) or Test Driven Development (TDD)
enabling the early detection of bugs and errors.

|*_Tech proficiency_*
|All team members are beginners in the majority of the technologies we're using, and this is our first endeavor
in developing a real-world application. As a result, all of us should contribute to the project as fullstack developers.

|===

=== 3. Convention Constraints

|===
| Constraint | Explanation

|*_Clean Code_*
|The code composing the application must prioritize clarity and cleanliness, facilitating comprehension and ease of
maintenance in the long term. We adhere to camelCase for JavaScript and PascalCase for React, ensuring clear and
descriptive names while steering clear of confusing prefixes. We need to adhere to the conventions of the
programming languages we're using, including https://jsdoc.app/[JavaScript] , https://html.spec.whatwg.org/[HTML]
and https://www.w3.org/Style/CSS/[CSS].

|*_Arc42_*
|The project utilizes https://arc42.org/[Arc42] for documentation purposes.

|*_Usability_*
|The application must be user-friendly, with a clean and intuitive interface that is easy to navigate.
The user experience should be seamless and engaging, with a focus on accessibility and adaptability.


|===