ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy

=== Technology Decisions

In order to develop an application that meets the expected quality criteria,
we have decided to use the following technologies, as they were the one given to us in the base project:

* *_JavaScript_*: Main programming language. It is used in both back and front end.
* *_React_*: JavaScript library used in the design of graphical user interfaces.
* *_ExpressJS_*: Framework built on the top of _Node.js_ and used in the backend.
* *_MongoDB_*: Several instances are used to persist the information of the app.
* *_Github_*: Used for versioning the proyect and as a mean of communication for the dev team.
* *_Docker_*: Used for the app deployment.
* *_Github actions_*: Used for testing purposes, app deployment and as a CI/CD tool.

=== Top-level Decomposition

We have decided to implement a microservices arquitecture, with diferrent modules
for different purpouses. For instance, we currently have the following microservices:

* *_User service_*: Service used to add new users.
* *_Auth service_*: Service used for the authentication of users.
* *_Gateway service_*: Service exposed to the public and used as a proxy to the two previous ones.
* *_Webapp service_*. Web application that uses the _gateway service_ to allow basic login and user features.
* *_Jordi service_*. Sevice to generate and return questions from the Wikidata API.
* *_Userhistory service_*. Service to generate the user's history and global ranking.
// TODO: Fill with the upcoming microservices

=== Decisions taken to achieve quality goals

|===
| Quality goal | Decision made

|*_Usability_*
|The user must be able to use the application without any doubt or trouble. For this purpouse,
we must use internationalice the app, so it can be used by people from different countries,
elect a good font and its size, and make the app responsive.

|*_Perfomance_*
|To enhance performance and minimize system overload, we are optimizing our requests to WikiData.
This strategic reduction in requests will help prevent service disruptions. Additionally,
we are upgrading our infrastructure by transitioning from an Azure B1s VM to a more robust Oracle Cloud VM.Standard.A1.Flex instance.
This new setup includes 4 OCPU cores, 24 GB of RAM, and 50 GB of storage. To further reduce the strain on our server,
we have adjusted all monitoring probes to collect data at 15-second intervals.

|*_Maintainability and Escalability_*
|The application must be well structured so the modifications or expansions that
will have to be made can be done in a simple way without having to modify the previous
code excessively. For it, along with a microservice structure we will make use of design patterns
and coding conventions to obtain a clean maintainable code.

To be more specific, the Gateway Pattern and the Single Responsibility Pattern define the architectural design principles that we will follow in our microservices implementation.
The Gateway Pattern will be used to provide a unified entry point for all external requests,
while the Single Responsibility Pattern will ensure that each microservice has a clear and specific responsibility.

|===


=== Organizational Decisions

We have taken the following organizational decisions:

* *_Tasks_*: We have decided to distribute the tasks equally per person so that everyone has approximately the same workload. We think it is a good idea that once a task is done, it should be reviewed by at least 50% of the group to be taken as valid.
* *_Github Issues_*: We make use of _Github Issues_ to create the tasks mentioned above and assign them to different team members. We will also use them to discuss any critical decisions that need to be made about the project.
* *_Github Projects_*: We also take into account _Github Projects_ to organize the workflow and to track the progress of the project.
* *_Language_*: We have agreed that we will develop the project in _English_ so the code and documentation will use it as the main language. This way we will guarantee that the project is accessible to everyone.
* *_External Meetings_*: We have decided to have meetings on a regular basis to discuss the progress of the project and to make decisions about the next steps to be taken.
* *_Internal Communication_*: We have decided to use Discord as the main communication channel for the project. We will use it to discuss any issues that arise during the development of the project. The support of Github Webhooks will be used to notify the team of any changes in the repository.
* *_Documentation_*: We have decided to use _Asciidoc_ as the main documentation tool. This is mainly because the deployment of the documentation is easier and more intuitive given the tools that Wiq0 provides.