global:
  scrape_interval: 15s
scrape_configs:
  - job_name: "example-nodejs-app"
    static_configs:
      - targets:
        - "gatewayservice:8000"
        - "userservice:8001"
        - "authservice:8002"
        - "jordi:8003"
        - "history:8004"
