openapi: 3.0.3
info:
  title: Ranking API specification
  description: Internal API that handles ranking data
  version: 1.0.1
servers:
  - url: 'http://localhost:8005'
paths:
  /ranking/{n}:
    get:
      summary: Get the top n users
      parameters:
        - name: n
          in: path
          required: true
          schema:
            type: integer
            example: 5
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      example: 'user'
                    points:
                      type: integer
                      example: 100
                    date:
                      type: string
                      format: date-time
                      example: '2021-01-01T00:00:00Z'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'An error occurred'
        '503':
          description: Service unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'Service unavailable'
  /adduser:
    post:
      summary: Add a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: 'user'
                score:
                  type: integer
                  example: 100
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Record added'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'Name not present'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'An error occurred'
        '503':
          description: Service unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'Service unavailable'