--DROP TRIGGER IF EXISTS TRIGGER_ADD_DATE_INSERT ON RECORD;
--DROP TRIGGER IF EXISTS TRIGGER_ADD_DATE_UPDATE ON RECORD;
--DROP FUNCTION IF EXISTS ADD_DATE;
DROP TABLE IF EXISTS RECORDS;

CREATE TABLE RECORDS (
    NAME VARCHAR(64),
    POINTS INT,
    DATE DATE
);

-- TODO - Fix

--CREATE OR REPLACE FUNCTION ADD_DATE()
--RETURNS TRIGGER
--LANGUAGE plpgsql
--BEGIN
--    IF NEW.DATE IS NULL THEN
--        NEW.DATE := NOW();
--    END IF;
--    RETURN NEW;
--END;
--;

--CREATE OR REPLACE TRIGGER TRIGGER_ADD_DATE_INSERT
--BEFORE INSERT ON RECORD
--FOR EACH ROW
--EXECUTE FUNCTION ADD_DATE();
--
--CREATE OR REPLACE TRIGGER TRIGGER_ADD_DATE_UPDATE
--BEFORE UPDATE ON RECORD
--FOR EACH ROW
--EXECUTE FUNCTION ADD_DATE();
