openapi: 3.0.3
info:
  title: Jordi API Specification
  description: Internal API that provides the questions and answers
  version: 1.0.1
servers:
  - url: 'http://localhost:8003'
components:
  schemas:
    Question:
      type: object
      properties:
        _id:
          type: string
          example: '5f9b3b3b7b3b7b3b7b3b7b3b'
        groupId:
          type: string
          example: 'group'
        categories:
          type: array
          items:
            type: string
            example: 'Category 1'
        statement:
          type: string
          example: 'Question 1'
        options:
          type: array
          items:
            type: string
            example: 'Option 1'
        answer:
          type: string
          example: 'Option 1'
paths:
  /categories:
    get:
      summary: Get all categories
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: 'Category 1'
        '500':
          description: 'Internal Server Error'
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'An error occurred'
        '503':
          description: 'Service Unavailable'
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'Service Unavailable'
  /questions/{category}/{n}:
    get:
      summary: Get n questions from a category
      parameters:
        - name: category
          in: path
          required: true
          schema:
            type: string
            example: 'Category 1'
        - name: n
          in: path
          required: true
          schema:
            type: integer
            example: 5
      responses:
        # TODO - 404 when category not found
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Question'
        '500':
          description: 'Internal Server Error'
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'An error occurred'
        '503':
          description: 'Service Unavailable'
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'Service Unavailable'
  /question/{id}:
    get:
      summary: Get a question by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: '5f9b3b3b7b3b7b3b7b3b7b3b'
      responses:
#        TODO - Add error mapping
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Question'