name: Build
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
    types: [opened, synchronize, reopened]
    
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm --prefix users/authservice ci
    - run: npm --prefix users/userservice ci
    - run: npm --prefix userhistory ci
    - run: npm --prefix gatewayservice ci
    - run: npm --prefix jordi ci
    - run: npm --prefix webapp ci
    - run: npm --prefix users/authservice test -- --coverage; cd gatewayservice; node sonarfix.js
    - run: npm --prefix users/userservice test -- --coverage; cd gatewayservice; node sonarfix.js
    - run: npm --prefix userhistory test -- --coverage; cd gatewayservice; node sonarfix.js
    - run: npm --prefix gatewayservice test -- --coverage; cd gatewayservice; node sonarfix.js
    - run: npm --prefix jordi test -- --coverage; cd gatewayservice; node sonarfix.js
    - run: npm --prefix webapp test -- --coverage; cd gatewayservice; node sonarfix.js

    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
