name: deploy-utils.yml
on:
  push:
    branches: [ master, develop, develop-package ]
    paths:
      - 'cyt-utils/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: cyt-utils
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get commit author and email
        run: |
          echo "COMMIT_AUTHOR_NAME=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
          echo "COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')" >> $GITHUB_ENV

      - name: Setup author info
        run: |
          git config --global user.name "${{ env.COMMIT_AUTHOR_NAME }}"
          git config --global user.email "${{ env.COMMIT_AUTHOR_EMAIL }}"

      - name: Publish package
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci

      - name: Increase version (patch)
        run: npm version patch
        if: github.ref == 'refs/heads/develop-package'

      - name: Increase version (minor)
        run: npm version minor
        if: github.ref == 'refs/heads/develop'

      - name: Increase version (major)
        if: github.ref == 'refs/heads/master'
        run: npm version major

      - run: npm publish
        working-directory: cyt-utils
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit changes
        run: |
          git config --global user.name "${{ env.COMMIT_AUTHOR_NAME }}"
          git config --global user.email "${{ env.COMMIT_AUTHOR_EMAIL }}"
          git add package.json
          git commit -m "Update package version"
          git push origin HEAD:${{ github.ref }}