name: Deploy on release

on:
  push:
    branches:
      - master

jobs:

  unit-tests:

    name: Unit tests
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    
    # TODO: Re-enable tests and coverage
  
    # - name: Setup Node.js 
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: 20

    # - run: npm --prefix users/authservice ci
    # - run: npm --prefix users/userservice ci
    # - run: npm --prefix gatewayservice ci
    # - run: npm --prefix webapp ci
    # - run: npm --prefix users/authservice test -- --coverage
    # - run: npm --prefix users/userservice test -- --coverage
    # - run: npm --prefix gatewayservice test -- --coverage
    # - run: npm --prefix webapp test -- --coverage
    
    # TODO: Add tests of the new microservices
    #

    # - name: Analyze with SonarCloud
    #   uses: sonarsource/sonarcloud-github-action@master
    #   env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  e2e-tests:

    name: End to end tests
    runs-on: ubuntu-latest
    needs: [unit-tests]

    steps:
    
    - name: Check out the repo
      uses: actions/checkout@v4

    # TODO: Re-enable when webapp tests match the current app desgin

    # - name: Setup Node.js 
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: 20

    # - run: npm --prefix users/authservice install
    # - run: npm --prefix users/userservice install
    # - run: npm --prefix gatewayservice install
    # - run: npm --prefix webapp install
    # - run: npm --prefix webapp run build

    # - run: npm --prefix webapp run test:e2e


  docker-push-webapp:
    
    name: Push webapp Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    needs: [e2e-tests]

    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Set up Docker Buildx # required for building multi-platform images
      uses: docker/setup-buildx-action@v1

    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: arquisoft/wiq_es05b/webapp
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        workdir: webapp
        buildargs: API_URI
        platforms: linux/arm64

    env:
        API_URI: http://${{ secrets.DEPLOY_HOST }}:8000


  docker-push-authservice:

    name: Push auth service Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    needs: [e2e-tests]

    permissions:
      contents: read
      packages: write

    steps:
    - name: Set up Docker Buildx # required for building multi-platform images
      uses: docker/setup-buildx-action@v1

    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
          name: arquisoft/wiq_es05b/authservice
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          workdir: users/authservice
          platforms: linux/arm64


  docker-push-userservice:

    name: Push user service Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    needs: [e2e-tests]

    permissions:
      contents: read
      packages: write

    steps:
    - name: Set up Docker Buildx # required for building multi-platform images
      uses: docker/setup-buildx-action@v1

    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: arquisoft/wiq_es05b/userservice
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        workdir: users/userservice
        platforms: linux/arm64


  docker-push-gatewayservice:

    name: Push gateway service Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    needs: [e2e-tests]

    permissions:
      contents: read
      packages: write

    steps:
    - name: Set up Docker Buildx # required for building multi-platform images
      uses: docker/setup-buildx-action@v1

    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: arquisoft/wiq_es05b/gatewayservice
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        workdir: gatewayservice
        platforms: linux/arm64


  docker-push-jordi-ask:

    name: Push Jordi Ask service Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    needs: [e2e-tests]

    permissions:
      contents: read
      packages: write

    steps:
    - name: Set up Docker Buildx # required for building multi-platform images
      uses: docker/setup-buildx-action@v1
    
    - name: Check out the repo
      uses: actions/checkout@v4
    
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: arquisoft/wiq_es05b/jordi-ask
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        workdir: jordi/jordi-ask
        platforms: linux/arm64


  docker-push-jordi-think:
    
    name: Push Jordi Think service Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    needs: [e2e-tests]
    
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Set up Docker Buildx # required for building multi-platform images
      uses: docker/setup-buildx-action@v1

    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: arquisoft/wiq_es05b/jordi-think
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        workdir: jordi/jordi-think
        platforms: linux/arm64


  docker-push-ranking:

    name: Push ranking service Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    needs: [e2e-tests]

    permissions:
      contents: read
      packages: write

    steps:
    - name: Set up Docker Buildx # required for building multi-platform images
      uses: docker/setup-buildx-action@v1
    
    - name: Check out the repo
      uses: actions/checkout@v4
    
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: arquisoft/wiq_es05b/ranking
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        workdir: ranking
        platforms: linux/arm64

        
  deploy:

    name: Deploy over SSH
    runs-on: ubuntu-latest
    needs: [docker-push-userservice,docker-push-authservice,docker-push-gatewayservice,docker-push-webapp,docker-push-jordi-ask,docker-push-jordi-think,docker-push-ranking]
    
    steps:
    - name: Deploy over SSH
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        user: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        
        command: |
            mkdir -p wiq_es05b
            cd wiq_es05b
            wget https://raw.githubusercontent.com/arquisoft/wiq_es05b/master/docker-compose.yml -O docker-compose.yml
            wget https://raw.githubusercontent.com/arquisoft/wiq_es05b/master/.env -O .env
            docker compose --profile prod down
            docker compose --profile prod up -d --pull always
